patterns:
  vip:
    - '\d{3}\d000$'
    - '(\d)(\d)0\1\2[0]{2}$'
    - '(\d{3})\1\1'
    - '(\d{5})\1'
    - '\d+(\d)\1\1\1$'
    - '(\d)\1\1[0]\1{3}$'
    - '.*8675309.*'
    - '(\d)(\d)\1\2\1\2$'
    - '^212.+'
  platinum:
    - '.*(\d){3}\d(\d)\2\2$'
    - '.*(\d{2})\1[0]0$'
    - '.*\d{3}(\d{3})[0]\1$'
  notable:
    - '(\d)(\d)(\d)(\d)(\d)\5\4\3\2\1'
    - '(\d)(\d)\1\2\1\2.+'
    - '((\d)(\d)(\2|\3){3})\1'
    - '(\d)(\d)\1\2\1.*(\d)(\d)\3\4\3'
    - '.*(\d)\1\1(\d)(\d)\2\3$'
    - '.*(\d)\1(\d)(\1|\2)\1\2\2$'
    - '.*(\d)(\d)(\d)\1\2\3(\1|\2|\3)$'
    - '.*(\d)\1\1(\d)\2\2\d$'
    - '.*\d{3}(\d{3})[1-9]\1$'
    - '.*(246)8\1$'
    - '.*(258)\1[08]$'
    - '.*\d\d(\d)(\d)(\d)(\d)\1\2\3\4$'
    - '.*(\d{2})(?!\1)(\d{2})00$'
    - '.*8449988.*'
