regions:
  default:
    - "202"
    - "212"
    - "213"
    - "303"
    - "310"
    - "313"
    - "415"
    - "416"
    - "418"
    - "512"
    - "514"
    - "617"
    - "808"
    - "907"
    - "~8449988"
  Canada:
    - "204"
    - "226"
    - "236"
    - "249"
    - "250"
    - "289"
    - "306"
    - "343"
    - "365"
    - "367"
    - "403"
    - "416"
    - "418"
    - "428"
    - "431"
    - "437"
    - "438"
    - "450"
    - "506"
    - "514"
    - "519"
    - "548"
    - "579"
    - "581"
    - "587"
    - "604"
    - "613"
    - "639"
    - "647"
    - "672"
    - "705"
    - "709"
    - "778"
    - "780"
    - "782"
    - "807"
    - "819"
    - "825"
    - "867"
    - "902"
    - "905"
  CA:
    - "209"
    - "213"
    - "310"
    - "323"
    - "408"
    - "415"
    - "424"
    - "442"
    - "510"
    - "530"
    - "559"
    - "562"
    - "619"
    - "626"
    - "650"
    - "661"
    - "669"
    - "707"
    - "714"
    - "760"
    - "805"
    - "818"
    - "831"
    - "858"
    - "909"
    - "916"
    - "925"
    - "949"
    - "951"
  NY:
    - "212"
    - "315"
    - "332"
    - "347"
    - "516"
    - "518"
    - "585"
    - "607"
    - "631"
    - "646"
    - "716"
    - "718"
    - "845"
    - "914"
    - "917"
    - "929"
    - "934"
  NYC:
    - "212"
    - "332"
    - "347"
    - "646"
    - "718"
    - "917"
    - "929"
  TX:
    - "210"
    - "214"
    - "254"
    - "281"
    - "325"
    - "346"
    - "361"
    - "409"
    - "430"
    - "432"
    - "469"
    - "512"
    - "682"
    - "713"
    - "806"
    - "817"
    - "830"
    - "903"
    - "915"
    - "936"
    - "940"
    - "956"
    - "972"
    - "979"
